sudo: required
language: python
script: 'python manage.py test'
after_success:
  - pip install virtualenv
  - virtualenv ~/env
  - source ~/env/bin/activate
  - pip install transifex-client
  - tx push -s
